/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        // Stitch exact palette
        "surface-bright": "#f9f9ff",
        "surface": "#f9f9ff",
        "surface-dim": "#cfdaf1",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "surface-container": "#e7eeff",
        "surface-container-high": "#dee8ff",
        "surface-container-highest": "#d8e3fa",
        "on-surface": "#111c2c",
        "on-surface-variant": "#43474f",
        "inverse-surface": "#263142",
        "inverse-on-surface": "#ebf1ff",
        "outline": "#747780",
        "outline-variant": "#c4c6d0",
        "surface-tint": "#415e91",
        "surface-variant": "#d8e3fa",
        // Primary — navy
        "primary": "#002451",
        "on-primary": "#ffffff",
        "primary-container": "#1a3a6b",
        "on-primary-container": "#89a5dd",
        "inverse-primary": "#abc7ff",
        "primary-fixed": "#d7e2ff",
        "primary-fixed-dim": "#abc7ff",
        "on-primary-fixed": "#001b3f",
        "on-primary-fixed-variant": "#284678",
        // Secondary — teal
        "secondary": "#006a66",
        "on-secondary": "#ffffff",
        "secondary-container": "#7df6ef",
        "on-secondary-container": "#00716d",
        "secondary-fixed": "#7df6ef",
        "secondary-fixed-dim": "#5ed9d3",
        "on-secondary-fixed": "#00201f",
        "on-secondary-fixed-variant": "#00504d",
        // Tertiary — dark grey
        "tertiary": "#212628",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#373b3e",
        "on-tertiary-container": "#a1a5a8",
        "tertiary-fixed": "#e0e3e6",
        "tertiary-fixed-dim": "#c3c7ca",
        "on-tertiary-fixed": "#181c1e",
        "on-tertiary-fixed-variant": "#43474a",
        // Error
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        // Background
        "background": "#f9f9ff",
        "on-background": "#111c2c",
      },
      fontFamily: {
        "hanken": ["Hanken Grotesk", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
        sans: ["Hanken Grotesk", "Inter", "system-ui", "sans-serif"],
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-xl-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
      spacing: {
        "xs": "4px",
        "sm": "12px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "container-margin-mobile": "16px",
        "max-width-desktop": "1200px",
        "sidebar-width": "260px",
        "container-max-width": "1440px",
        "gutter": "24px",
        "margin-desktop": "40px",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        card: "0 4px 12px rgba(26,58,107,0.04)",
        modal: "0 8px 24px rgba(26,58,107,0.08)",
      },
    },
  },
  plugins: [],
};
